package domain

import "time"

// Session is a single authenticated device session for a user. Sessions group
// refresh-token families: every Login or CompleteOAuth creates a session, and
// every refresh-token belongs to exactly one session/family.
//
// The session row survives across refresh-token rotations, so a user can list
// "active sessions" (logged-in devices) and revoke them wholesale.
type Session struct {
	ID          string
	UserID      string
	DeviceLabel string // optional, client-supplied ("iPhone 15", "Chrome/Mac")
	FamilyID    string // the refresh-token family rooted at this session
	CreatedAt   time.Time
	LastSeenAt  time.Time
	ExpiresAt   time.Time
}

// NewSession constructs a Session for the given user. familyID is generated by
// the use case (a fresh ULID) and shared by every refresh token issued within
// this session. ExpiresAt is the session's lifetime ceiling — refreshing does
// not extend it past this point.
func NewSession(now time.Time, id, userID, familyID string, ttl time.Duration, deviceLabel string) Session {
	return Session{
		ID:          id,
		UserID:      userID,
		FamilyID:    familyID,
		DeviceLabel: deviceLabel,
		CreatedAt:   now,
		LastSeenAt:  now,
		ExpiresAt:   now.Add(ttl),
	}
}

// IsExpired reports whether the session has passed its lifetime ceiling.
func (s Session) IsExpired(now time.Time) bool {
	return !now.Before(s.ExpiresAt)
}

// Touch updates LastSeenAt. Called on every successful token use so the
// "active sessions" list reflects real activity.
func (s *Session) Touch(now time.Time) {
	s.LastSeenAt = now
}
